set(dir "${WORK}/key-fixture")
file(MAKE_DIRECTORY "${dir}")
file(WRITE "${dir}/stops.txt" "stop_id\ns\n")
file(WRITE "${dir}/routes.txt" "route_id\nr\n")
file(WRITE "${dir}/calendar_dates.txt" "service_id,date,exception_type\nc,20261008,1\n")
file(WRITE "${dir}/shapes.txt" "shape_id\nf\n")
file(WRITE "${dir}/trips.txt" "trip_id,route_id,service_id,shape_id\nt,r,c,f\n")
file(WRITE "${dir}/stop_times.txt" "trip_id,stop_id\nt,s\n")
execute_process(COMMAND "${EXE}" validate-keys "${dir}" RESULT_VARIABLE valid)
if(NOT valid EQUAL 0)
  message(FATAL_ERROR "Valid relational fixture rejected")
endif()
file(WRITE "${dir}/stop_times.txt" "trip_id,stop_id\nt,missing\n")
execute_process(COMMAND "${EXE}" validate-keys "${dir}" RESULT_VARIABLE invalid)
if(invalid EQUAL 0)
  message(FATAL_ERROR "Dangling reference accepted")
endif()
